Revert "build(deps): bump google-auth from 2.29.0 to 2.30.0 in /api"
This reverts commit 926a0135e1a1541a844a6bfcf1dcc2d3a4412d2c.

mypy reports 2 warnings with this new version:

    src/pcapi/core/auth/api.py:30:47: error: "Credentials" has no attribute "service_account_email"  [attr-defined]
    src/pcapi/core/auth/api.py:33:17: error: "Credentials" has no attribute "service_account_email"  [attr-defined]

We must fix that but it does not seem that easy. Revert first, fix
later.