search: Fix import loop when `core.search` is imported early
Avoid this:

    Traceback (most recent call last):
      File "/src/pcapi/scheduled_tasks/algolia_clock.py", line 4, in <module>
        from pcapi.core import search
      File "/src/pcapi/core/search/__init__.py", line 5, in <module>
        import pcapi.core.offers.models as offers_models
      File "/src/pcapi/core/offers/models.py", line 36, in <module>
        from pcapi.models.db import Model
      File "/src/pcapi/models/__init__.py", line 8, in <module>
        from pcapi.core.offerers.models import ApiKey
      File "/src/pcapi/core/offerers/models.py", line 33, in <module>
        from pcapi.core.offers.models import Offer
    ImportError: cannot import name 'Offer' from partially initialized module 'pcapi.core.offers.models' (most likely due to a circular import) (/src/pcapi/core/offers/models.py)

Enough is enough. I'll fix that import mess next Friday...