(BSR)[API] fix: avoid circular import
Traceback (most recent call last):
  File "/usr/src/app/src/pcapi/scripts/.../main.py", line 16, in <module>
    from pcapi.core.users import api as users_api
  File "/usr/src/app/src/pcapi/core/users/api.py", line 31, in <module>
    import pcapi.core.offerers.api as offerers_api
  File "/usr/src/app/src/pcapi/core/offerers/api.py", line 32, in <module>
    import pcapi.core.offers.api as offers_api
  File "/usr/src/app/src/pcapi/core/offers/api.py", line 22, in <module>
    import pcapi.core.bookings.api as bookings_api
  File "/usr/src/app/src/pcapi/core/bookings/api.py", line 62, in <module>
    from . import validation
  File "/usr/src/app/src/pcapi/core/bookings/validation.py", line 13, in <module>
    from pcapi.core.users.api import get_domains_credit
ImportError: cannot import name 'get_domains_credit' from partially initialized module 'pcapi.core.users.api' (most likely due to a circular import) (/usr/src/app/src/pcapi/core/users/api.py)